### ISSUE TITLE
Pehkui size compatibility issue

### ISSUE THREAD

**Issue by HyperlyBola** [MrFantiVideo/MineGate#29]
When changing to an origin while using the Pehkui mod to change the player size, the camera doesn't scale with the player in first person. I tested with and without Minegate and noticed Minegate is causing the issue

https://www.curseforge.com/minecraft/mc-mods/pehkui

**Comment by MrFantiVideo** [comment]
Hello,

MineGate also changes the size of the entity with potions / effects, I don't see how to solve this problem.

**Comment by HyperlyBola** [comment]
Sorry for reviving this issue.
Is there a way I could entirely remove the CameraMixin? I'm fairly certain that is causing the compatibility issue, and I don't really use the potions/effects. When I tried removing the CameraMixin and the Potions they still showed up after building. I'm not sure if I missed something.

My friends just really want to play with smaller origins such as the moth, while also using minegate. I don't know anything about modding.

**Comment by MrFantiVideo** [comment]
Yes, it is the mixin on the Camera that is the problem.

For this to work, you must:
- Removed the « CameraMixin.java » class.
- Remove it from the list in the « minegate.mixins.json » file.
Return to the source folder, type in the address bar of the folder « cmd » and do the command « gradlew build » and go to « build/libs » and you will have the modified mod version.

I can optionally put an option that disables the change of camera, but this may be a problem because when you become small for example, you can go below the block.

If you delete the potions, it will cause other bugs.
But if you have any suggestions for improvement on the size change, please do not hesitate.

**Comment by HyperlyBola** [comment]
I followed the instructions, removing the CameraMixin file entirely, and removing it from the clients section of the mixins file, yet after building it and testing the issue was still there. 

If it isn't much trouble, adding a config option for toggling camera changes would be great!

The only suggestion I have for fixing this compatibility issue, is to have an option to enable "pekhui compatibility" that disables the built-in minegate scaling, and uses the pekhui scaling for any effects that need scaling. Pekhui has commands such as `/scale set <value> [entity]` and `/scale get [entity]` 

Here's the mod page https://www.curseforge.com/minecraft/mc-mods/pehkui?page=26

**Comment by MrFantiVideo** [comment]
Fixed in the new version. ([MoreBlocks 1.2.3](https://github.com/MrFantiVideo/MineGate/releases/tag/1.2.3))
You must disable the « changeSize » option in the « minegate.json » if you want to use another mod that changes the size of entities.
