### ISSUE TITLE
Leaves Loot Tables

### ISSUE THREAD

**Issue by CanINotUseTruth** [MrFantiVideo/MineGate#6]
The loot tables you have set up in version 1.1.5 for at least Oak Leaves causes the block to drop and not apples and sticks etc. I'm not sure if this is intentional but it also means there is no way of getting saplings from trees.

**Comment by MrFantiVideo** [comment]
Hello,

Fix for the next version of the mod. (I was informed on Discord, this was not intentional.)
If you want with the problem to correct, here is a version of the mod with the modified files.

[minegate-moreblocks-1.1.5_fix_sapling](https://github.com/MrFantiVideo/MineGate/files/6800944/minegate-moreblocks-1.1.5_fix_sapling.zip)

Thank you for your contribution.
